[package]
name = "bipper"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version="1.0.188",  features = ["derive"] }
sqlx = { version = "0.7", features = [ "runtime-async-std", "postgres" ] }
serde_json = "1.0.105"
anyhow = "1.0.75"
tempfile = "3.8.0"
bip39 = "2.0.0"
rand = "0.8.5"
scrypt = { version = "0.11", default-features = false }
aes-gcm = "0.10.2"
hex = "0.4.3"
dotenv = "0.15.0"
tokio = { version = "1.32.0", features = ["full"] }
axum = { version = "0.6.20", features = [ "multipart" ]}
hyper = { version = "0.14.27", features = ["full"] }
tower = "0.4.13"
tracing-subscriber = "0.3.17"
tracing = "0.1.37"
futures-util = "0.3.28"
