version: '3.1'
services:
  bipper:
    image: bipper
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./store:/store
    environment:
      - RUST_LOG=INFO
      - BIPPER_POSTGRES_HOST=${BIPPER_POSTGRES_HOST}
      - BIPPER_POSTGRES_PORT=${BIPPER_POSTGRES_PORT}
      - BIPPER_POSTGRES_USER=${BIPPER_POSTGRES_USER}
      - BIPPER_POSTGRES_DATABASE=${BIPPER_POSTGRES_DATABASE}
      - BIPPER_POSTGRES_PASSWORD=${BIPPER_POSTGRES_PASSWORD}
      - BIPPER_ADDRESS=${BIPPER_ADDRESS}
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:${BIPPER_POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${BIPPER_POSTGRES_PASSWORD}
      - POSTGRES_USER=${BIPPER_POSTGRES_USER}
      - POSTGRES_DB=${BIPPER_POSTGRES_DATABASE}
