version: '3.1'
services:
  bipper:
    build: .
    image: bipper
    restart: unless-stopped
    container_name: "bipper"
    environment:
      - RUST_LOG=DEBUG
    networks:
      - web
      - default
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - "./migrations:/docker-entrypoint-initdb.d"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: bipper
    networks:
      - default
networks:
  web:
    external: true
  default:
